 # odev 10
print("╔════════════════════════════════════════╗")
print("║                                        ║")
print("║                                        ║")
print("║                                        ║")
print("║               NOT DEFTERİ              ║")
print("║                                        ║")
print("║         1-Yeni Not                     ║")
print("║                                        ║")
print("║         2-Kaydedilen notlar            ║")
print("║                                        ║")
print("║         3-Ayarlar                      ║")
print("║                                        ║")
print("║         4-Kaynak Lisanları             ║")
print("║                                        ║")
print("║                                        ║")    
print("║             Surum 1.9.3                ║")
print("╚════════════════════════════════════════╝")
